#!/usr/bin/env python

import sys
import optparse
import os.path

from walkerLexer import Lexer
from walkerParser import Parser
from walkerWalker import Walker


def wc(fpin, fpout):
	lexer = Lexer(fpin)
	parser = Parser(lexer)
	parser.grammar()
	ast = parser.getAST()

	writer = Walker(fpout)
	writer.start(ast)
	

def main():
	parser = optparse.OptionParser(usage="\n\t%prog [options] file ...", version="%prog 1.0")
	parser.add_option('-o', '--output', type="string", dest="output", help="Output file")
	(options, args) = parser.parse_args(sys.argv[1:])

	for arg in args:
		fpin = file(arg, 'rt')

		if options.output is None:
			root, ext = os.path.splitext(arg)
			fpout = file(root + '.py', 'wt')
		elif options.output is '-':
			fpout = sys.stdout
		else:
			fpout = file(options.output, 'wt')

		wc(fpin, fpout)


if __name__ == '__main__':
	main()
